class_name TrucoData
extends JugadorData	

enum TipoEfecto {
	EXPULSAR_CARTA_ENEMIGA,
	EXPULSAR_CARTA_PROPIA,
	BUFF_ATAQUE_COLUMNA,
	BUFF_VIDA_COLUMNA,
	DANIO_DIRECTO,
	ROBAR_CARTAS,
	BUFF_ALL_STATS,
	ATAQUE_DOBLE_COLUMNA,
	INMUNIDAD_ARCO,
	EXPULSAR_BARATOS,
	BUFF_ATAQUE_JUGADOR,
	CURAR_VIDA,
	DANIO_DIRECTO_PASANTE,
	DANIO_ARCO_DIRECTO,
	BUFF_VELOCIDAD_COLUMNA,
	REDUCIR_VIDA_COLUMNA,
	BUFF_ATAQUE_ALL,
	DEBUFF_ATAQUE_ALL,
}

@export var tipo_efecto: TipoEfecto =TipoEfecto.EXPULSAR_CARTA_ENEMIGA
@export var valor: int =0
@export var es_universal: bool= false
